/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.yet.spring;

import com.yet.spring.bean.Client;
import com.yet.spring.bean.Event;
import com.yet.spring.logger.EventLogger;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {
    Client client;
    EventLogger eventLogger;

    public App(Client client, EventLogger eventLogger) {
        this.client = client;
        this.eventLogger = eventLogger;
    }

    void logEvent(Event event) {
        String message = event.getMsg().replaceAll(client.getId(), client.getFullName());
        event.setMsg(message);
        eventLogger.logEvent(event);
    }

    public static void main(String[] args) {
        ConfigurableApplicationContext ctx = new ClassPathXmlApplicationContext("spring.xml");

        App app = ctx.getBean(App.class);
        Event event = ctx.getBean(Event.class);
        event.setMsg("Some event for user 1");
        app.logEvent(event);
        event = ctx.getBean(Event.class);
        event.setMsg("Some event for user 2");
        app.logEvent(event);
        event = ctx.getBean(Event.class);
        event.setMsg("Some event for user 3");
        app.logEvent(event);

        ctx.close();
    }
}
